version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: yarn
      - run: yarn test:coverage
      - run: yarn codecov
      - store_artifacts:
          path: ~/project/coverage/lcov-report/

workflows:
  version: 2
  main:
    jobs:
      - test
